services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    env_file: .env
    command: >
     --requirepass $REDIS_PASSWORD

  web:
    image: tmnd_image
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    image: tmnd_image
    env_file: .env
    command: python manage.py rqworker default
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
      - web
    deploy:
      mode: replicated
      replicas: 1
